### ISSUE TITLE
wiring

### ISSUE THREAD

**Issue by Sebbeben** [muellerjo/PT100-ESP8266#1]
hi do you have wiring schematics for this?

**Comment by muellerjo** [comment]
Hi @Sebbeben
thank you very much, for the Issue.
It gave me the necessary pressure, to create the schematics, that are now available in the repositroy.
[Link to Schematic](https://github.com/muellerjo/PT100-ESP8266/blob/master/resources/Sketch_Schaltplan.png)
Please let me know about any further issues.
Thank you very much, kind regard, Jonas

**Comment by Sebbeben** [comment]
Great! Thank you very much :)

thanks for sharing this project, nice work :)
